### PR TITLE
Updated Docker file

### PR DESCRIPTION
**Pull request by jurakp**
Removed SES region property to make it agnostic

@ianwestcott Once merged, let me know, I'll try to execute GH action.

### CODE REVIEW

**Comment by ianwestcott** [comment]
@jurakp side-note: At the moment, the "Deploy" GitHub Actions are still pulling container images from the ECR repo in the shared SSO AWS account. So you didn't need me to merge this PR in order to deploy 1.0.7, you just needed to push the image to ECR. I noticed that you already did that on the 11th, so I ran the GitHub Action to deploy 1.0.7 to Keycloak Prod a little while ago in order to unblock @krisrjohnson21's testing. You're welcome to try deploying 1.0.7 to Keycloak Dev. 😄 

With all that said: Now that the code is here, I plan on adding GitHub Actions to build container images from this GitHub repo and push them to the ECR repo in our main AWS account. So everything I just said above will change soon, hopefully later this week. I'll keep your team posted.

**Review by ianwestcott — COMMENTED** [review]
Does `files/keycloak-modules/keycloak-model-infinispan/keycloak-model-infinispan-15.0.2-integsoft-1.jar` replace `files/keycloak-model-infinispan-15.0.2.jar`? If so, can you delete the old one?

**Comment by jurakp** [comment]
@ianwestcott It's done. Actually it worked, but the jar file was redundant. So now it is removed.

**Comment by jurakp** [comment]
@ianwestcott Regarding ECR: the latest image (1.0.7) was deployed before to Dev (sandbox), so it's not blocking. The only problem was that we pushed unused jar file to GH.
Once the image build is done by GH action, it would be great! +1

**Comment by jurakp** [comment]
@ianwestcott FYI: I ran GH action for Dev.

**Review by ianwestcott — APPROVED** [review]

**Pull request merged**
